#Time::DATE_FORMATS[:default] = "%d.%m.%Y at %H:%M:%S"
#Date::DATE_FORMATS[:default] = "%d.%m.%Y"
Time::DATE_FORMATS[:datetime] = "%d.%m.%Y %H:%M:%S"
Time::DATE_FORMATS[:default] = "%H:%M"
Date::DATE_FORMATS[:default] = "%d.%m.%Y"
Time::DATE_FORMATS[:log] = "%d.%m. %H:%M:%S"