defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  host: localhost

development:
  database: remoteassistant_development
  <<: *defaults

test: &test
  database: remoteassistant_test
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  host: localhost

production:
  database: remoteassistant_production
  <<: *defaults

