defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: remoteassistant
  password: secret

development:
  database: remoteassistant_development
  <<: *defaults

test: &test
  database: remoteassistant_test
  <<: *defaults

production:
  database: remoteassistant_development
  <<: *defaults
