development:
  key: aaa
  secret: xxx
  bucket: yyy

production:
  key: <%= ENV["S3_KEY"] %>
  secret: <%= ENV["S3_SECRET"] %>
  bucket: <%= ENV["S3_BUCKET"] %>

test:
  key: UNDEFINED
  secret: UNDEFINED
  bucket: UNDEFINED


